added test and changed in schema-file
egmontecom/dbt-egmont-product-explorer pull request #3
Opened 2021-06-14 13:26 UTC by johanneslarssonYE

2021-06-14 13:30 UTC, martenlindblad commented on models/product_explorer/pe_schema.yml
> +              field: brand
can we fold all the columnsexists to the same list?

2021-06-15 06:37 UTC, johanneslarssonYE commented on models/product_explorer/pe_schema.yml
> +              field: brand
that's not possible

2021-06-15 09:00 UTC, martenlindblad requested changes

2021-06-15 09:00 UTC, martenlindblad commented on models/product_explorer/pe_schema.yml
> +          - columnsexists:
I think I understand the test process. Really good.  But could we maybe rename the fields? Or are they fixed?
I don't really understand what `to` does in this context.

2021-06-15 09:03 UTC, martenlindblad requested changes

2021-06-15 09:03 UTC, martenlindblad commented on models/product_explorer/pe_schema.yml
> +
database: royaldesign-311208 should not be here please :)

2021-06-15 09:20 UTC, martenlindblad commented on models/product_explorer/pe_schema.yml
> +
Will create new issue for this issue

2021-06-15 10:58 UTC, merged