Brand health
egmontecom/dbt-egmont-product-explorer pull request #35
Opened 2021-08-27 08:00 UTC by hmmoek

2021-09-01 19:25 UTC, martenlindblad requested changes
Ser riktigt bra ut, några enkla saker som måste fixas, samt några generella frågor bara.

2021-09-01 19:25 UTC, martenlindblad commented on models/product_explorer/in_stock_percentage.sql
> +    from `royaldesign-311208.transformed.all_products_stock_value_by_day`
använd source.yml!

2021-09-01 19:25 UTC, martenlindblad commented on models/product_explorer/in_stock_percentage.sql
> +    from `royaldesign-311208.transformed.transformed_WP_sales`
använd source.yml!

2021-09-03 09:05 UTC, hmmoek commented
I think we will wait with the changes on brand health, and fix the whole code later.

2021-09-03 09:06 UTC, hmmoek commented on models/product_explorer/brand_health.sql
> +        count(a.product_sku) over (partition by brand_name) custom_style_name_count
Verkar bli samma sak

2021-09-03 09:09 UTC, merged