Revenue lost oos
egmontecom/dbt-egmont-product-explorer pull request #54
Opened 2021-09-17 13:58 UTC by hmmoek

2021-09-18 12:40 UTC, johanneslarssonYE requested changes
The reason why you're not getting any hits are because its product _ids from "skus_purchasable_when_oos" and not product_skus. You can find prodcut_id -> product_sku mapping in: storm_products_all.

2021-09-23 07:35 UTC, johanneslarssonYE commented on models/product_explorer/revenue_lost_oos.sql
>      where stock_date>date_sub(current_date(), interval 365 day) and stock_qty>0
Småsak, men interval 1 year kanske? Annars tycker jag att du borde byta till >= för att få med 365e dagen också.

2021-09-23 08:07 UTC, hmmoek commented on models/product_explorer/revenue_lost_oos.sql
>      where stock_date>date_sub(current_date(), interval 365 day) and stock_qty>0
Om jag har >=365 så får vi 366 dagar, och vi vill bara ha 365

2021-10-04 11:46 UTC, martenlindblad approved these changes

2021-10-04 12:00 UTC, merged